/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.LoginController;
import Model.Banco;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author Fernnd
 */
public class Login extends javax.swing.JFrame {

    private final LoginController controller;
    public Login() {
        initComponents();
        controller = new LoginController(this);
        Banco.Inicia();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UNIDENTES = new javax.swing.JLabel();
        Usuario = new javax.swing.JLabel();
        Senha = new javax.swing.JLabel();
        textUsuario = new javax.swing.JTextField();
        Esqueceu = new javax.swing.JLabel();
        botaoLogin = new javax.swing.JButton();
        textSenha = new javax.swing.JPasswordField();
        iconCirculo = new javax.swing.JLabel();
        iconDente = new javax.swing.JLabel();
        telaFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1200, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UNIDENTES.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        UNIDENTES.setForeground(new java.awt.Color(255, 255, 255));
        UNIDENTES.setText("UNIDENTES");
        getContentPane().add(UNIDENTES, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, -1, -1));

        Usuario.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        Usuario.setText("Usuario");
        getContentPane().add(Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, -1, -1));

        Senha.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        Senha.setText("Senha");
        getContentPane().add(Senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 270, -1, -1));

        textUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(textUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 220, 290, 40));

        Esqueceu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Esqueceu.setText("Esqueceu a senha?");
        getContentPane().add(Esqueceu, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 310, -1, -1));

        botaoLogin.setText("Entrar");
        botaoLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLoginActionPerformed(evt);
            }
        });
        getContentPane().add(botaoLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 350, 290, 40));

        textSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(textSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 300, 290, 40));

        iconCirculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons/aaaaa-removebg-preview (1).png"))); // NOI18N
        getContentPane().add(iconCirculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        iconDente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons/dental_tooth_icon_149293.png"))); // NOI18N
        getContentPane().add(iconDente, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, -1, -1));

        telaFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Login.jpg"))); // NOI18N
        getContentPane().add(telaFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-420, -40, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textUsuarioActionPerformed

    private void botaoLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLoginActionPerformed
        this.controller.entrarSistema();
    }//GEN-LAST:event_botaoLoginActionPerformed

    private void textSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textSenhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Esqueceu;
    private javax.swing.JLabel Senha;
    private javax.swing.JLabel UNIDENTES;
    private javax.swing.JLabel Usuario;
    private javax.swing.JButton botaoLogin;
    private javax.swing.JLabel iconCirculo;
    private javax.swing.JLabel iconDente;
    private javax.swing.JLabel telaFundo;
    private javax.swing.JPasswordField textSenha;
    private javax.swing.JTextField textUsuario;
    // End of variables declaration//GEN-END:variables

    
    public JPasswordField getTextSenha() {
        return textSenha;
    }
    
    public JTextField getTextUsuario() {
        return textUsuario;
    }

    public void setTextUsuario(JTextField textUsuario) {
        this.textUsuario = textUsuario;
    }

    public void exibeMensagem(String mensagem) {
        JOptionPane.showMessageDialog(null, mensagem);
    }
        
}
