/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.TelaInicialController;
import java.awt.Color;

/**
 *
 * @author Fernnd
 */
public class TelaInicial extends javax.swing.JFrame {

    private final TelaInicialController controller;
    public TelaInicial() {
        initComponents();
        
        controller = new TelaInicialController(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BotaoAgenda = new javax.swing.JButton();
        BotaoUsuario = new javax.swing.JButton();
        BotaoPacientes = new javax.swing.JButton();
        BotaoEstoque = new javax.swing.JButton();
        BotaoAnalise = new javax.swing.JButton();
        BotaoTelaInicial = new javax.swing.JButton();
        BotaoFinanceiro = new javax.swing.JButton();
        Titulo = new javax.swing.JLabel();
        IconTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BotaoAgenda.setBackground(new java.awt.Color(173, 216, 230));
        BotaoAgenda.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        BotaoAgenda.setText("Agenda");
        BotaoAgenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotaoAgendaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotaoAgendaMouseExited(evt);
            }
        });
        BotaoAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoAgendaActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoAgenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 170, 80));

        BotaoUsuario.setBackground(new java.awt.Color(173, 216, 230));
        BotaoUsuario.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        BotaoUsuario.setText("Usuário");
        BotaoUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotaoUsuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotaoUsuarioMouseExited(evt);
            }
        });
        BotaoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 170, 80));

        BotaoPacientes.setBackground(new java.awt.Color(173, 216, 230));
        BotaoPacientes.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        BotaoPacientes.setText("Pacientes");
        BotaoPacientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotaoPacientesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotaoPacientesMouseExited(evt);
            }
        });
        BotaoPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoPacientesActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoPacientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 170, 80));

        BotaoEstoque.setBackground(new java.awt.Color(173, 216, 230));
        BotaoEstoque.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        BotaoEstoque.setText("Estoque");
        BotaoEstoque.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotaoEstoqueMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotaoEstoqueMouseExited(evt);
            }
        });
        BotaoEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoEstoqueActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoEstoque, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 170, 80));

        BotaoAnalise.setBackground(new java.awt.Color(173, 216, 230));
        BotaoAnalise.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        BotaoAnalise.setText("Análise de Dados");
        BotaoAnalise.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotaoAnaliseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotaoAnaliseMouseExited(evt);
            }
        });
        BotaoAnalise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoAnaliseActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoAnalise, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 620, 170, 80));

        BotaoTelaInicial.setBackground(new java.awt.Color(173, 216, 230));
        BotaoTelaInicial.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        BotaoTelaInicial.setText("Tela Inicial");
        BotaoTelaInicial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotaoTelaInicialMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotaoTelaInicialMouseExited(evt);
            }
        });
        BotaoTelaInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoTelaInicialActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoTelaInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 170, 80));

        BotaoFinanceiro.setBackground(new java.awt.Color(173, 216, 230));
        BotaoFinanceiro.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        BotaoFinanceiro.setText("Financeiro");
        BotaoFinanceiro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotaoFinanceiroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotaoFinanceiroMouseExited(evt);
            }
        });
        BotaoFinanceiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoFinanceiroActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoFinanceiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, 170, 80));

        Titulo.setFont(new java.awt.Font("Sitka Small", 1, 58)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setText("Consultas");
        getContentPane().add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 30, -1, -1));

        IconTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons/aaaaa-removebg-preview (2).png"))); // NOI18N
        getContentPane().add(IconTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, -100, -1, 340));

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabela);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 950, 580));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Odonto Blue.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 1280, 730));

        jMenu1.setText("Opções");

        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/icons/icons8-login-arredondado-à-direita-30.png"))); // NOI18N
        jMenuItem1.setText("Sair");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoTelaInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoTelaInicialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoTelaInicialActionPerformed

    private void BotaoTelaInicialMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoTelaInicialMouseEntered
        controller.aoPassarMouse(BotaoTelaInicial);
    }//GEN-LAST:event_BotaoTelaInicialMouseEntered

    private void BotaoTelaInicialMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoTelaInicialMouseExited
        controller.aoTirarMouse(BotaoTelaInicial);
    }//GEN-LAST:event_BotaoTelaInicialMouseExited

    private void BotaoAgendaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoAgendaMouseEntered
        controller.aoPassarMouse(BotaoAgenda);
    }//GEN-LAST:event_BotaoAgendaMouseEntered

    private void BotaoAgendaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoAgendaMouseExited
        controller.aoTirarMouse(BotaoAgenda);
    }//GEN-LAST:event_BotaoAgendaMouseExited

    private void BotaoUsuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoUsuarioMouseEntered
       controller.aoPassarMouse(BotaoUsuario);
    }//GEN-LAST:event_BotaoUsuarioMouseEntered

    private void BotaoUsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoUsuarioMouseExited
        controller.aoTirarMouse(BotaoUsuario);
    }//GEN-LAST:event_BotaoUsuarioMouseExited

    private void BotaoPacientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoPacientesMouseEntered
       controller.aoPassarMouse(BotaoPacientes);
    }//GEN-LAST:event_BotaoPacientesMouseEntered

    private void BotaoPacientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoPacientesMouseExited
        controller.aoTirarMouse(BotaoPacientes);
    }//GEN-LAST:event_BotaoPacientesMouseExited

    private void BotaoEstoqueMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoEstoqueMouseEntered
        controller.aoPassarMouse(BotaoEstoque);
    }//GEN-LAST:event_BotaoEstoqueMouseEntered

    private void BotaoEstoqueMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoEstoqueMouseExited
        controller.aoTirarMouse(BotaoEstoque);
    }//GEN-LAST:event_BotaoEstoqueMouseExited

    private void BotaoFinanceiroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoFinanceiroMouseEntered
        controller.aoPassarMouse(BotaoFinanceiro);
    }//GEN-LAST:event_BotaoFinanceiroMouseEntered

    private void BotaoFinanceiroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoFinanceiroMouseExited
        controller.aoTirarMouse(BotaoFinanceiro);
    }//GEN-LAST:event_BotaoFinanceiroMouseExited

    private void BotaoAnaliseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoAnaliseMouseEntered
        controller.aoPassarMouse(BotaoAnalise);
    }//GEN-LAST:event_BotaoAnaliseMouseEntered

    private void BotaoAnaliseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoAnaliseMouseExited
        controller.aoTirarMouse(BotaoAnalise);
    }//GEN-LAST:event_BotaoAnaliseMouseExited

    private void BotaoAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoAgendaActionPerformed
       controller.entrarAgenda();
    }//GEN-LAST:event_BotaoAgendaActionPerformed

    private void BotaoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoUsuarioActionPerformed
        controller.entrarUsuario();
    }//GEN-LAST:event_BotaoUsuarioActionPerformed

    private void BotaoPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoPacientesActionPerformed
        controller.entrarPacientes();
    }//GEN-LAST:event_BotaoPacientesActionPerformed

    private void BotaoEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoEstoqueActionPerformed
        controller.entrarEstoque();
    }//GEN-LAST:event_BotaoEstoqueActionPerformed

    private void BotaoFinanceiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoFinanceiroActionPerformed
        controller.entrarFinanceiro();
    }//GEN-LAST:event_BotaoFinanceiroActionPerformed

    private void BotaoAnaliseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoAnaliseActionPerformed
        controller.entrarAnalise();
    }//GEN-LAST:event_BotaoAnaliseActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        controller.Sair();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoAgenda;
    private javax.swing.JButton BotaoAnalise;
    private javax.swing.JButton BotaoEstoque;
    private javax.swing.JButton BotaoFinanceiro;
    private javax.swing.JButton BotaoPacientes;
    private javax.swing.JButton BotaoTelaInicial;
    private javax.swing.JButton BotaoUsuario;
    private javax.swing.JLabel IconTitulo;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
